[package]
name = "kitchen"
version = "0.1.0"
authors = ["Waritnan Sookbuntherng <lion328@hotmail.co.th>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
zip = "0.5"
csv = "1.1"
md5 = "0.7"
bytes = "1"